pipeline:
  name: hey
  identifier: hey
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gelo
        repoName: sample-java-app
        build: <+input>
  stages:
    - stage:
        name: clone
        identifier: clone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: tes
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: gelo
                    repoName: sample-java-app
                    build:
                      type: branch
                      spec:
                        branch: main
